<a href="https://colab.research.google.com/github/khalidpark/deeplearning_whitepaper/blob/main/deep_learning_whitepaper_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 파일 선택을 통해 예제 데이터를 내 컴퓨터에서 불러오는 코드를 포함(주석)
# 강의 목적상 내 데이터를 대신하여 서버에서 불러오도록 하겠습니다. 직접 가지고 있는 데이터를 사용하기 위해서는 주석처리된 files.upload()를 이용하시면 됩니다.
from google.colab import files
#uploaded = files.upload() # 파일을 불러올 수 있는 코드

# 폐암 수술 환자의 특정기간 생존 데이터
# 속성(정보)은 종양의 유형, 폐활량, 호흡곤란 여부, 기침, 흡연, 천식여부 등의 17가지 환자 상태. 수술 후 생존(1), 사망(0) 
my_data = "https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/everydeep/ThoraricSurgery.csv"

# 딥러닝을 구동하는 데 필요한 케라스 함수를 불러옵니다.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow.keras.layers as Layer

# 케라스 외의 필요한 라이브러리를 불러옵니다.
import numpy as np
import pandas as pd
import tensorflow as tf

# 실행할 때마다 같은 결과를 출력하기 랜덤함수를 고정하는 부분입니다.
# 랜덤함수의 Seed를 고정하게 되면 랜덤함수가 항상 일정하게 나옵니다. 
np.random.seed(3)
tf.random.set_seed(3)

# 불러온 데이터를 적용합니다.
# pandas외에도 읽을 수 있는 방법이 있습니다. 편하신 방법을 사용하시면 됩니다.
Data_set = np.loadtxt(my_data, delimiter=",")

In [2]:
Data_set = pd.read_csv(my_data, header=None) 
Data_set.describe()

               0           1           2   ...          15          16          17
count  470.000000  470.000000  470.000000  ...  470.000000  470.000000  470.000000
mean   235.500000    3.095745    3.281638  ...    0.004255   62.534043    0.148936
std    135.821574    0.722309    0.871395  ...    0.065163    8.706902    0.356405
min      1.000000    1.000000    1.440000  ...    0.000000   21.000000    0.000000
25%    118.250000    3.000000    2.600000  ...    0.000000   57.000000    0.000000
50%    235.500000    3.000000    3.160000  ...    0.000000   62.000000    0.000000
75%    352.750000    3.000000    3.807500  ...    0.000000   69.000000    0.000000
max    470.000000    8.000000    6.300000  ...    1.000000   87.000000    1.000000

[8 rows x 18 columns]

In [3]:
Data_set = np.loadtxt(my_data, delimiter=",") 
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장합니다.
X = Data_set[:,0:17]
Y = Data_set[:,17]

# 딥러닝 구조를 결정합니다(모델을 설정하고 실행하는 부분입니다).
model = Sequential([
    Dense(30, input_dim=17, activation='relu'),
    Layer.Dropout(0.5),
    Dense(30, input_dim=17, activation='relu'),
    Dense(1, activation='sigmoid') # 분류할 방법에 따라 개수를 조정해야 합니다. 
])
# 딥러닝을 실행합니다.
model.compile(loss='mean_squared_logarithmic_error', optimizer='adam', metrics=['accuracy']) # mean_squared_error # binary_crossentropy # mean_absolute_error # poisson
history = model.fit(X, Y, epochs=30, batch_size=30)

Epoch 1/30
16/16 [==============================] - 1s 2ms/step - loss: 0.1923 - accuracy: 0.5833
Epoch 2/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0986 - accuracy: 0.7804
Epoch 3/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0887 - accuracy: 0.8106
Epoch 4/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0765 - accuracy: 0.8378
Epoch 5/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0742 - accuracy: 0.8453
Epoch 6/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0683 - accuracy: 0.8559
Epoch 7/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0735 - accuracy: 0.8452
Epoch 8/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0753 - accuracy: 0.8432
Epoch 9/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0669 - accuracy: 0.8616
Epoch 10/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0632 - accuracy: 0.8710
Epoch 11/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0731 - accuracy: 0.8474
Epoch 12/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0805 - accuracy: 0.8310
Epoch 13/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0854 - accuracy: 0.8202
Epoch 14/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0758 - accuracy: 0.8424
Epoch 15/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0763 - accuracy: 0.8415
Epoch 16/30
16/16 [==============================] - 0s 3ms/step - loss: 0.0669 - accuracy: 0.8595
Epoch 17/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0668 - accuracy: 0.8570
Epoch 18/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0704 - accuracy: 0.8547
Epoch 19/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0764 - accuracy: 0.8424
Epoch 20/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0664 - accuracy: 0.8596
Epoch 21/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0734 - accuracy: 0.8475
Epoch 22/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0684 - accuracy: 0.8580
Epoch 23/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0703 - accuracy: 0.8541
Epoch 24/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0741 - accuracy: 0.8449
Epoch 25/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0787 - accuracy: 0.8356
Epoch 26/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0695 - accuracy: 0.8552
Epoch 27/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0729 - accuracy: 0.8465
Epoch 28/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0749 - accuracy: 0.8437
Epoch 29/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0598 - accuracy: 0.8733
Epoch 30/30
16/16 [==============================] - 0s 2ms/step - loss: 0.0544 - accuracy: 0.8865